package com.intellij.terarosa.common;

public enum SiGunGuCategory {

    Jonglo("종로구",SidoCategory.Seoul),
    Jung1("중구",SidoCategory.Seoul),
    Youngsan("용산구",SidoCategory.Seoul),
    Sungdong("성동구",SidoCategory.Seoul),
    Gwangjin("광진구",SidoCategory.Seoul),
    Dongdaemun("동대문구",SidoCategory.Seoul),
    Junglang("중랑구",SidoCategory.Seoul),
    Sungbuk("성북구",SidoCategory.Seoul),
    Gangbuk("강북구",SidoCategory.Seoul),
    Dobong("도봉구",SidoCategory.Seoul),
    Nowon("노원구",SidoCategory.Seoul),
    Eunpyeong("은평구",SidoCategory.Seoul),
    Seodaenum("서대문구",SidoCategory.Seoul),
    Mapo("마포구",SidoCategory.Seoul),
    Yangcheon("양천구",SidoCategory.Seoul),
    Gangseo1("강서구",SidoCategory.Seoul),
    Guro("구로구",SidoCategory.Seoul),
    Geumcheon("금천구",SidoCategory.Seoul),
    Yungdeungpo("영등포구",SidoCategory.Seoul),
    Dongjak("동작구",SidoCategory.Seoul),
    Gwanak("관악구",SidoCategory.Seoul),
    Seocho("서초구",SidoCategory.Seoul),
    Gangnam("강남구",SidoCategory.Seoul),
    Songpa("송파구",SidoCategory.Seoul),
    Gangdong("강동구",SidoCategory.Seoul),

    Jung2("중구",SidoCategory.Busan),
    Seo("서구",SidoCategory.Busan),
    Dong("동구",SidoCategory.Busan),
    Yungdo("영도구",SidoCategory.Busan),
    Basanjin("부산진구",SidoCategory.Busan),
    Dongre("동래구",SidoCategory.Busan),
    Namgu("남구",SidoCategory.Busan),
    Dukgu("북구",SidoCategory.Busan),
    Gangseo2("강서구",SidoCategory.Busan),
    Haeundae("해운대구",SidoCategory.Busan),
    Saha("사하구",SidoCategory.Busan),
    Geumjeong("금정구",SidoCategory.Busan),
    Yeonjae("연제구",SidoCategory.Busan),
    Suyoung("수영구",SidoCategory.Busan),
    Sasang("사상구",SidoCategory.Busan),
    Gijang("가장군",SidoCategory.Busan),

    Jung3("중구",SidoCategory.Daegu),
    Dong2("동구",SidoCategory.Daegu),
    Seo2("서구",SidoCategory.Daegu),
    Nam("남구",SidoCategory.Daegu),
    Buk("북구",SidoCategory.Daegu),
    Susung("수성구",SidoCategory.Daegu),
    Dalseo("달서구",SidoCategory.Daegu),
    Dalsung("달성군",SidoCategory.Daegu),

    Jung4("중구",SidoCategory.Incheon),
    Dong3("동구",SidoCategory.Incheon),
    Michuhol("미추홀구",SidoCategory.Incheon),
    Yeonsu("연수구",SidoCategory.Incheon),
    Namdong("남동구",SidoCategory.Incheon),
    Bupyeong("부평구",SidoCategory.Incheon),
    Gyeyang("계양구",SidoCategory.Incheon),
    Seo3("서구",SidoCategory.Incheon),
    Ganghwa("강화군",SidoCategory.Incheon),
    Ongjin("옹진군",SidoCategory.Incheon),

    Dong4("동구",SidoCategory.Gwangju),
    Seo4("서구",SidoCategory.Gwangju),
    Nam2("남구",SidoCategory.Gwangju),
    Buk2("북구",SidoCategory.Gwangju),
    Gwangsan("광산구",SidoCategory.Gwangju),

    Dong5("동구",SidoCategory.Daejeon),
    Jung5("중구",SidoCategory.Daejeon),
    Seo5("서구",SidoCategory.Daejeon),
    Usung("유성구",SidoCategory.Daejeon),
    Deduck("대덕구",SidoCategory.Daejeon),

    Jung6("중구",SidoCategory.Ulsan),
    Nam3("남구",SidoCategory.Ulsan),
    Dong6("동구",SidoCategory.Ulsan),
    Buk3("북구",SidoCategory.Ulsan),
    Ulju("울주군",SidoCategory.Ulsan),

    Sejong("세종시",SidoCategory.Sejong),

    Suwon("수원시",SidoCategory.Gyeonggi),
    Sungnam("성남시",SidoCategory.Gyeonggi),
    Anyang("안양시",SidoCategory.Gyeonggi),
    Ansan("안산시",SidoCategory.Gyeonggi),
    Yongin("용인시",SidoCategory.Gyeonggi),
    Bucheon("부천시",SidoCategory.Gyeonggi),
    Gwangmyeong("광명시",SidoCategory.Gyeonggi),
    PyeongTek("평택시",SidoCategory.Gyeonggi),
    Gwacheon("과천시",SidoCategory.Gyeonggi),
    Osan("오산시",SidoCategory.Gyeonggi),
    Siheung("시흥시",SidoCategory.Gyeonggi),
    Gunpo("군포시",SidoCategory.Gyeonggi),
    Euiwang("의왕시",SidoCategory.Gyeonggi),
    Hanam("하남시",SidoCategory.Gyeonggi),
    Icheon("이천시",SidoCategory.Gyeonggi),
    Ansung("안성시",SidoCategory.Gyeonggi),
    Gimpo("김포시",SidoCategory.Gyeonggi),
    Hwasung("화성시",SidoCategory.Gyeonggi),
    Gwangju("광주시",SidoCategory.Gyeonggi),
    Yeoju("여주시",SidoCategory.Gyeonggi),
    Yangpyeong("양평군",SidoCategory.Gyeonggi),
    Goyang("고양시",SidoCategory.Gyeonggi),
    Euijeongbu("의정부시",SidoCategory.Gyeonggi),
    Dongducheon("동두천시",SidoCategory.Gyeonggi),
    Guri("구리시",SidoCategory.Gyeonggi),
    Namyangju("남양주시",SidoCategory.Gyeonggi),
    Yangju("양주시",SidoCategory.Gyeonggi),
    Pocheon("포천시",SidoCategory.Gyeonggi),
    Yeoncheon("연천군",SidoCategory.Gyeonggi),
    Gapyeong("가평군",SidoCategory.Gyeonggi),

    Chuncheon("춘천시",SidoCategory.Gangwon),
    Wonju("원주시",SidoCategory.Gangwon),
    Gangreung("강릉시",SidoCategory.Gangwon),
    Donghe("동해시",SidoCategory.Gangwon),
    Tebek("태백시",SidoCategory.Gangwon),
    Sokcho("속초시",SidoCategory.Gangwon),
    Samchuck("삼척시",SidoCategory.Gangwon),
    HongCheon("홍천군",SidoCategory.Gangwon),
    HwingSung("횡성군",SidoCategory.Gangwon),
    Yungwol("영월군",SidoCategory.Gangwon),
    pyeongchang("평창군",SidoCategory.Gangwon),
    jungsun("정선군",SidoCategory.Gangwon),
    chulwon("철원군",SidoCategory.Gangwon),
    Hwacheon("화천군",SidoCategory.Gangwon),
    Yanggu("양구군",SidoCategory.Gangwon),
    Injae("인제군",SidoCategory.Gangwon),
    Gosung("고성군",SidoCategory.Gangwon),
    Yangyang("양양군",SidoCategory.Gangwon),

    Chungju("청주시",SidoCategory.Chungbuk),
    Choongju("충주시",SidoCategory.Chungbuk),
    Jecheon("제천시",SidoCategory.Chungbuk),

    Boeun("보은군",SidoCategory.Chungbuk),
    Okcheon("옥천군",SidoCategory.Chungbuk),
    Yungdong("영동군",SidoCategory.Chungbuk),
    jeungpyeong("증평군",SidoCategory.Chungbuk),
    jincheon("진천군",SidoCategory.Chungbuk),
    Guisan("괴산군",SidoCategory.Chungbuk),
    Eumsung("음성군",SidoCategory.Chungbuk),
    Danyanh("단양군",SidoCategory.Chungbuk),

    Seogwipo("서귀포시",SidoCategory.Jeju),
    Jeju("제주시",SidoCategory.Jeju),

    Changwon("창원시",SidoCategory.Gyeongnam),
    Jinju("진주시",SidoCategory.Gyeongnam),
    Tongyeong("통영시",SidoCategory.Gyeongnam),
    Sacheon("사천시",SidoCategory.Gyeongnam),
    Gimhae("김해시",SidoCategory.Gyeongnam),
    Miryang("밀양시",SidoCategory.Gyeongnam),
    Geoje("거제시",SidoCategory.Gyeongnam),
    Yangsan("양산시",SidoCategory.Gyeongnam),
    Uiryeong("의령군",SidoCategory.Gyeongnam),
    Haman("함안군",SidoCategory.Gyeongnam),
    Changnyeong("창녕군",SidoCategory.Gyeongnam),
    Goseong("고성군",SidoCategory.Gyeongnam),
    Namhae("남해군",SidoCategory.Gyeongnam),
    Hadong("하동군",SidoCategory.Gyeongnam),
    Sancheong("산청군",SidoCategory.Gyeongnam),
    Hamyang("함양군",SidoCategory.Gyeongnam),
    Geochang("거창군",SidoCategory.Gyeongnam),
    Hapcheon("합천군",SidoCategory.Gyeongnam),

    Pohang("포항시",SidoCategory.Gyeongbuk),
    Gyeongju("경주시",SidoCategory.Gyeongbuk),
    Gimcheon("김천시",SidoCategory.Gyeongbuk),
    Andong("안동시",SidoCategory.Gyeongbuk),
    Gumi("구미시",SidoCategory.Gyeongbuk),
    Yeongju("영주시",SidoCategory.Gyeongbuk),
    Yeongcheon("영천시",SidoCategory.Gyeongbuk),
    Sangju("상주시",SidoCategory.Gyeongbuk),
    Mungyeong("문경시",SidoCategory.Gyeongbuk),
    Gyeongsan("경산시",SidoCategory.Gyeongbuk),
    Gunwi("군위군",SidoCategory.Gyeongbuk),
    Uiseong("의성군",SidoCategory.Gyeongbuk),
    Cheongsong("청송군",SidoCategory.Gyeongbuk),
    Yeongyang("영양군",SidoCategory.Gyeongbuk),
    Yeongdeok("영덕군",SidoCategory.Gyeongbuk),
    Cheongdo("청도군",SidoCategory.Gyeongbuk),
    Goryeong("고령군",SidoCategory.Gyeongbuk),
    Seongju("성주군",SidoCategory.Gyeongbuk),
    Chilgok("칠곡군",SidoCategory.Gyeongbuk),
    Yecheon("예천군",SidoCategory.Gyeongbuk),
    Bonghwa("봉화군",SidoCategory.Gyeongbuk),
    Uljin("울진군",SidoCategory.Gyeongbuk),
    Ulleung("울릉군",SidoCategory.Gyeongbuk),


    Mokpo("목포시",SidoCategory.Jeonnam),
    Yeosu("여수시",SidoCategory.Jeonnam),
    Suncheon("순천시",SidoCategory.Jeonnam),
    Naju("나주시",SidoCategory.Jeonnam),
    Gwangyang("광양시",SidoCategory.Jeonnam),
    Damyang("담양군",SidoCategory.Jeonnam),
    Gokseong("곡성군",SidoCategory.Jeonnam),
    Gurye("구례군",SidoCategory.Jeonnam),
    Goheung("고흥군",SidoCategory.Jeonnam),
    Boseong("보성군",SidoCategory.Jeonnam),
    Hwasun("화순군",SidoCategory.Jeonnam),
    Jangheung("장흥군",SidoCategory.Jeonnam),
    Gangjin("강진군",SidoCategory.Jeonnam),
    Haenam("해남군",SidoCategory.Jeonnam),
    Yeongam("영암군",SidoCategory.Jeonnam),
    Muan("무안군",SidoCategory.Jeonnam),
    Hampyeong("함평군",SidoCategory.Jeonnam),
    Yeonggwang("영광군",SidoCategory.Jeonnam),
    Jangseong("장성군",SidoCategory.Jeonnam),
    Wando("완도군",SidoCategory.Jeonnam),
    Jindo("진도군",SidoCategory.Jeonnam),
    Sinan("신안군",SidoCategory.Jeonnam),

    Jeonju("전주시",SidoCategory.Jeonbuk),
    Gunsan("군산시",SidoCategory.Jeonbuk),
    Iksan("익산시",SidoCategory.Jeonbuk),
    Jeongeup("정읍시",SidoCategory.Jeonbuk),
    Namwon("남원시",SidoCategory.Jeonbuk),
    Gimje("김제시",SidoCategory.Jeonbuk),
    Wanju("완주군",SidoCategory.Jeonbuk),
    Jinan("진안군",SidoCategory.Jeonbuk),
    Muju("무주군",SidoCategory.Jeonbuk),
    Jangsu("장수군",SidoCategory.Jeonbuk),
    Imsil("임실군",SidoCategory.Jeonbuk),
    Sunchang("순창군",SidoCategory.Jeonbuk),
    Gochang("고창군",SidoCategory.Jeonbuk),
    Buan("부안군",SidoCategory.Jeonbuk),

    Cheonan("천안시",SidoCategory.Chungnam),
    Gongju("공주시",SidoCategory.Chungnam),
    Boryeong("보령시",SidoCategory.Chungnam),
    Asan("아산시",SidoCategory.Chungnam),
    Seosan("서산시",SidoCategory.Chungnam),
    Nonsan("논산시",SidoCategory.Chungnam),
    Gyeryong("계룡시",SidoCategory.Chungnam),
    Dangjin("당진시",SidoCategory.Chungnam),
    Geumsan("금산군",SidoCategory.Chungnam),
    Buyeo("부여군",SidoCategory.Chungnam),
    Seocheon("서천군",SidoCategory.Chungnam),
    Cheongyang("청양군",SidoCategory.Chungnam),
    Hongseong("홍성군",SidoCategory.Chungnam),
    Yesan("예산군",SidoCategory.Chungnam),
    Taean("태안군",SidoCategory.Chungnam),
    ;
    public String name;
    public SidoCategory sidoCategory;

    SiGunGuCategory(String name, SidoCategory sidoCategory) {
        this.name = name;
        this.sidoCategory = sidoCategory;
    }

}
